See CHANGELOG for v3.0.0
node-fetch/fetch-blob pull request #83
Opened 2021-04-20 18:23 UTC by jimmywarting

## v3.0.0
- Changed WeakMap for private field (require node 12)
- Switch to ESM
- blob.stream() return a subset of whatwg stream which is the async iterable
  (it no longer return a node stream - now it returns a AsyncGenerator)
- Reduced the dependency of Buffer by changing to global TextEncoder/Decoder (require node 11)
- Disabled xo since it could understand private fields (#)
- No longer transform the type to lowercase (https://github.com/w3c/FileAPI/issues/43)
  This is more loose than strict, keys should be lowercased, but values should not.
  It would require a more proper mime type parser - so I just made it loose.
- index.js can now be imported by browser & deno from a CDN since it no longer depends on any
  core node features and dose not bundle anything to commonjs

2021-04-20 18:47 UTC, jimmywarting commented
Change CI node version to something higher?

2021-04-20 18:49 UTC, jimmywarting commented
Change CI node version to something higher?

2021-04-21 00:10 UTC, Richienb requested changes

2021-04-21 00:10 UTC, Richienb commented on index.js
> +export { Blob };
```suggestion
export default Blob;
```

2021-04-21 07:33 UTC, jimmywarting commented on index.js
> +export { Blob };
My idea was to have both so you could do `{Blob} = await import('fetch-blob')` instead of dealing with the keyword default, but sure i can change

2021-04-21 07:45 UTC, Richienb commented on index.js
> +export { Blob };
Can't you just do `const Blob = await import("fetch-blob")`?

2021-04-21 07:51 UTC, jimmywarting commented on index.js
> +export { Blob };
if you only have a default you would have to do 

```js
import Blob from 'fetch-blob'

const { default: Blob } = await import('fetch-blob')`
const blob = await import('fetch-blob').then(module => module.default)
```
if you have a named version as well then you can do

```js
import Blob from 'fetch-blob'

const { Blob } = await import('fetch-blob')`
import('fetch-blob').then(({ Blob }) => {
  // ...
})
```

2021-04-21 15:01 UTC, tinovyatkin reviewed
👍🏻 cool stuff!

2021-04-21 15:39 UTC, jimmywarting commented on index.js
> +	 * @param {(ArrayBufferLike | ArrayBufferView | Blob | string)[]} blobParts
When should @param ever have the Readonly? isn't Read Only just for properties?
Also I was thinking... when i helped out on node's core Blob then the blobParts was very strict at what it could accept... in the real case the default fallback behavior is to cast anything that isn't a buffer or a blob into a string

It's perfectly fine to do `new Blob([true, null, 0, Infinity])` in the browser, so maybe `@params blobParts` should be `@param {Any} BlobParts`? It accepts a another blob like item such as the one backed up by the filesystem also...

2021-04-21 15:45 UTC, jimmywarting commented on index.js
> +					while (position !== end) {
I stole this piece of code from a node-fetch PR i made.
The problem with nodes `new buffer.Blob([]).slice(0, 5)` was that it thrown a error when slicing something outside of the size range. So i had to use `Math.min` to stop exactly at the end position

Could you think of any test I could write that verifies that it works as intended?

2021-04-21 15:46 UTC, jimmywarting commented on index.js
> +export { Blob };
Changing to `export class` and keeping the named export then!

2021-04-21 15:49 UTC, jimmywarting commented on test.js
> +});
Want to add `/** @see https://github.com/w3c/FileAPI/issues/43 */` above this test since it diverge from what the browser dose and there might be intentions to change this behavior in the spec

2021-04-21 16:27 UTC, tinovyatkin commented on index.js
> +	 * @param {(ArrayBufferLike | ArrayBufferView | Blob | string)[]} blobParts
> When should @param ever have the Readonly? isn't Read Only just for properties?

Probably the best answer will be this: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/prefer-readonly-parameter-types.md

> so maybe @params blobParts should be @param {Any} BlobParts?
As a TypeScript developer I would prefer `@param {unknown} blobPars`, as a Javascript developer I would prefer `@param {*} blobParts` then

2021-04-21 19:08 UTC, jimmywarting commented on index.js
> +	 * @param {(ArrayBufferLike | ArrayBufferView | Blob | string)[]} blobParts
Now, when i think of it readonly can make sense in arguments too. `crypto.getRandomBytes` is one such function that mutates the argument. while a forEach would not. So knowing if something is readonly makes a bit of since. I have never thought about arguments as readonly.
...Only about such things as eg the FileList on `input.files` and other similar things on `navigator`

Never really liked TypeScript since it requires a compile step and you can't import them in browser or in node without compiling it on the fly (it's like having two JIT compiler...) But I do however like the typescript+allowJs combo with jsDoc - so I write typescript compatible syntax in many cases

2021-04-21 19:20 UTC, jimmywarting commented
Only remaning question now is: 
What to do with [workflows/ci.yml](https://github.com/node-fetch/fetch-blob/blob/master/.github/workflows/ci.yml) to make the test pass? Probably have to change engine in package.json to something higher also... what is the lowest node support for ESM?

2021-04-22 10:16 UTC, tinovyatkin commented
> What to do with [workflows/ci.yml](https://github.com/node-fetch/fetch-blob/blob/master/.github/workflows/ci.yml) to make the test pass? Probably have to change engine in package.json to something higher also... what is the lowest node support for ESM?

It was unflagged in 13.x release, then backported into 12.x. I would put something like 12.13 - the release when 12.x becomes LTS

2021-04-24 20:55 UTC, octet-stream commented on index.js
> +	async * stream() {
Hey, can I open a PR to bring async version of `blobFrom` by making `BlobDataItem#stream()` async iterable, since it is a private object, used just to produce another `Blob` with a reference to a file on disk. I would love to have an async version of this function, since we're talking about Node.js here. And it seems like you're making same thing for class `Blob` anyway.
Also, I already implemented this and as far as I can tell everything is work perfectly.

2021-04-24 23:54 UTC, jimmywarting commented on index.js
> +	async * stream() {
Hmm, blobFrom should not be such a expensive operation, the only thing it dose is stat-ing some information about the file there shouldn't be much blocking about getting file size and last modified date.
but sure, we could have a async version of it too if you wish

`BlobDataItem#stream()` is already async iterable... it returns a readable stream that already have a `Symbol.asyncIterator` in its prototype (coming from `fs.createReadableStream(path))` - there is nothing synchronous about that. 
So I do not know why you are mentioning `BlobDataItem#stream()`

> And it seems like you're making same thing for class Blob anyway.

And what is that exactly? Both BlobDataItem#stream and Blob#stream have always been async iterable even before this PR...

> Also, I already implemented this and as far as I can tell everything is work perfectly.

May i have a look on it? Should we include it in this PR for v3?

2021-04-25 01:34 UTC, octet-stream commented on index.js
> +	async * stream() {
> blobFrom should not be such a expensive operation

Yes, I know that you're using `fs.statSync` under the hood (in `fromBlob` to get the size and `mtime`, then again in `.stream()` to compare two `mtime` value) which is not that expensive, and I saw an issue recently in Node.js repository with `fs.stat` vs `fs.statSync` vs `fs.promises.stat`, the `fs.statSync` was the fastest. I was just thinking is that, since Node.js has both sync and async stat methods, would be nice to add an async fromBlob here as well.

> May i have a look at it? Should we include it in this PR for v3?

Sure, but this change is meant to be for the current version. It doesn't break anything, since I only change private API and I also tested implementation. You can find it [here](https://github.com/octet-stream/fetch-blob/blob/bd536695cddfac04eb3e344492c3976f3dffe1b5/from.js). Note that tests may fail, if you'll try to run them because of [this issue](https://github.com/node-fetch/fetch-blob/pull/85).

> And what is that exactly? Both BlobDataItem#stream and Blob#stream have always been async iterable even before this PR...

In current version `BlobDataItem#stream()` will return ReadStream, yes, which is async iterable. But the method itself is not an async function or async generator function, which will allow using `fs.promises.stat` while being backward compatible with that Blob expect from blob-ish part.

2021-04-25 08:23 UTC, jimmywarting commented on index.js
> +	async * stream() {
Now I understand why you also made `BlobDataItem#stream()` iterable... it was b/c of `fs.promises.stat`

2021-04-25 12:17 UTC, octet-stream commented on index.js
> +	async * stream() {
Exactly

2021-04-25 18:47 UTC, octet-stream commented on from.js
> +import {statSync, createReadStream, promises as fs} from 'fs';
I think you can use `fs/promises` instead to get promise version of `stat` when you're in ESM context.

2021-04-25 18:51 UTC, octet-stream commented on from.js
> +export {Blob, blobFrom, blobFromAsync};
I think it would be better to keep naming style as it done for Node.js builtin libraries: `blobFrom` and `blobFromSync`.

2021-04-25 19:06 UTC, jimmywarting commented on index.js
> +	async * stream() {
Hello again, I implemented a async stat version of it into v3
basically took what you did [here](https://github.com/octet-stream/fetch-blob/blob/bd536695cddfac04eb3e344492c3976f3dffe1b5/from.js#L56-L67) and also used the promisified stat version like you did

My test used `text()` instead of `getStream()` since it could not handle async iterable. but it will test the same kind of bug

I also notice a other bug when reading empty files since it will always add -1 at the end to make the correct `end` from `size` when creating a readStream so i did work around it by looking at the file size first

I also made sure that `start` defaults to 0 instead of looking for undefined

---

- This started out with a sync version and the default still export the sync version (but with a async stat inside of stream() instead) 
- now you can import both using `import {blobFrom, blobFromSync}`
- would it be okey to exclude the async version from v2 and just make it a v3 feature?

--- 

should backport that zero size bug and your #85 to v2

2021-04-25 19:24 UTC, octet-stream commented on from.js
> +	lastModified: Number(stat.mtime),
Remind me... the `mtime` returns the Date object? And then you convert it to number to get milliseconds? If so, why don't you just use `mtimeMs` instead? This should be the same. Pretty much - it will return decimal number, at least on macOS.

2021-04-25 19:41 UTC, octet-stream commented on index.js
> +	async * stream() {
> would it be okey to exclude the async version from v2 and just make it a v3 feature?

I don't really mind whether it will be included in v2 or not. I just would love to bring async version of `fileFromPath` in `formdata-node` which is backed by `fetch-blob/from`.

2021-04-26 10:14 UTC, jimmywarting commented on from.js
> +	lastModified: Number(stat.mtime),
You are right, switched to `mtimeMs`

2021-04-26 10:15 UTC, jimmywarting commented on from.js
> +export {Blob, blobFrom, blobFromAsync};
fixed/replaced

2021-04-26 10:15 UTC, jimmywarting commented on from.js
> +import {statSync, createReadStream, promises as fs} from 'fs';
Ty, didn't know that, fixed

2021-04-27 01:01 UTC, octet-stream commented on from.js
>  			throw new DOMException('The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired.', 'NotReadableError');
I'm just curious: What is that error for? Is this just a browser thing made for compatibility reasons or is it a thing for Node.js too? What could happen when you read a modified file using the reference acquired before those changes were made?

2021-04-27 07:40 UTC, jimmywarting commented on from.js
>  			throw new DOMException('The requested file could not be read, typically due to permission problems that have occurred after a reference to a file was acquired.', 'NotReadableError');
Blob should be and they are immutable.
If they are modified and you already have a blob references then it could have unexpected consequences.
`blob.size` would not be the same size... A hash would not be the same.
+ it's something browser dose as well.

Browsers do not read the Files content from the filesystem in order to save memory until you actually need to read it.

2021-04-29 12:59 UTC, octet-stream commented on index.js
> +	async * stream() {
It seems like [I can only import ES modules in CJS using the `import()`](https://nodejs.org/dist/latest/docs/api/esm.html#esm_require), which means I will not be able to use 3.x version in `formdata-node` because I support both CJS and ESM build there and I want to keep CJS around until I release 4.x version of my library (I need to import `fetch-blob` in synchronous context, because `.set()`, `.append()` and `fileFromPathSync` have to be synchronous). So I think I have to send a PR anyway or just forget about this functionality until `formdata-node@4.x` release, which is not coming anytime soon, because 3.x was released just a month ago.

2021-05-02 16:17 UTC, lastthyme approved these changes

2021-05-02 18:42 UTC, jimmywarting commented
Would like to publish this to npm as 3.0.0-rc.0 and begin to roll it out for testing.

But wondering first a bit about #51 so we don't do any more breaking changes...
- I'm still in favor of the partial support of the whatwg `blob.stream()` as a async generator rather than having nothing at all. And leaving this PR as is.
- I would like for it to be isomorphic, So you can call `for await (const chunk of blob.stream()) { ... }` no mather what kind of stream/iterator it is. 
- I do not wish to import the hole whatwg stream polyfill just for a spec compatible readable stream - simply to much IMO + it don't fit so well suited in the Node ecosystem to use whatwg stream in Node (yet?)
- We strive towards being spec compatible and having a Node-stream or a async generator is a different behavior. So is having a different none standard name like `blob.toAsyncIterator()` that later have to be depricated once/if Node decide to add whatwg streams. that other also need to learn about and adopt to "known differences between other blobs"
  - I don't feel like we have had much complain/comments/discussion about having a none-standard node-readable `stream()` (only from one person?) for as long as we fetch-blob have existed.

ofc, you could iterate over a blob by slicing 'n reading `blob.slice(x, y).arrayBuffer()` yourself. but this feels like a _**#developer-pain**_

I think this can be easily subclassed/upgraded in user-land by either upgrading our `Blob.stream()` iterator/generator, polyfiling browsers ReadableStream iterator so `for-await-of` can be used everywhere. see 51#issuecomment-827088954 for more discussion/solution about this

Would have been nice if the blob spec had `@@symbol.asyncIterator` that you could iterate over the blob so `for await (let chunk of blob)` worked (spec proposal maybe) (feels a bit redundant when you can get hold of the iterator by simply calling `stream()` but browsers ReadableStream iterator isn't implemented anywhere yet)

Would like to hear someones else opinion also - don't want this to be one sided

One thing is for certain, need to update the readme with a section of "known differences" that basically only talks about `stream()`

2021-05-04 14:07 UTC, xxczaki commented
@jimmywarting 

> Do someone else agree with me or do you think it's bad to have a none spec generator instead of a whatwg stream with symbol.asyncIterator?

I vehemently agree with you - until there is no official & stable WHATWG stream support in Node.js, it's best to do the isomorphic approach with `AsyncGenerator`.

> (...) discussion in #51

I read the discussion. If we want to make `fetch-blob` web-compatible (and therefore not take the **node**-fetch) approach), we can do what the issue author suggested.

> Some folks already depend on our blob#stream() method and it would be even more breaking to remove it entirely then what it already is by downgrading our node-stream into a generator function and making it dependency-free from nodejs

👍

2021-05-04 14:08 UTC, xxczaki approved these changes
Great job.

2021-05-07 01:55 UTC, jimmywarting commented
will release 3.0.0-rc.0 tomorrow if there are no objections, never good to do release durning the night

2021-05-07 09:42 UTC, merged